### ISSUE TITLE
npx spago init fails using git bash on windows

### ISSUE THREAD

**Issue by Neppord** [purescript/spago#1305]
```
$ npx spago init
file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:48911
                  throw util.fromLeft(step3);
                  ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:83989:18
    at runSync (file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:48568:21)
    at run16 (file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:48761:25)
    at file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:48777:23
    at drain (file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:48595:9)
    at Object.enqueue (file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:48613:11)
    at file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:48771:31
    at __do4 (file:///D:/spago-next-test/node_modules/spago/bin/bundle.js:86427:77) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v22.8.0
```

Do not know what even is failing, since the error message contains very little information.

**Comment by Neppord** [comment]
I also tested with `Node.js v23.3.0`

**Comment by Neppord** [comment]
This seams to be related with using git bash, it works if you run it in powershell.

It is the first time I have had this issue with node, that I can remember so far.

**Comment by s5bug** [comment]
Failing in PowerShell too
```
PS C:\Users\aprim\Documents\pslua-test> spago init
file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:48911
                  throw util.fromLeft(step3);
                  ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:753:9)
    at file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:83989:18
    at runSync (file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:48568:21)
    at run16 (file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:48761:25)
    at file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:48777:23
    at drain (file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:48595:9)
    at Object.enqueue (file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:48613:11)
    at file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:48771:31
    at __do4 (file:///C:/Users/aprim/AppData/Roaming/nvm/v23.3.0/node_modules/spago/bin/bundle.js:86427:77) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v23.3.0
```
